# Generated by Django 4.0.4 on 2023-08-13 12:11

import ckeditor_uploader.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Noticia',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=300, verbose_name='Título da Postagem')),
                ('slug', models.SlugField(blank=True, default=None, max_length=300, null=True, unique=True)),
                ('imagen', models.ImageField(help_text='Notifique-se que o tamanho da Imagem é de. <b>Ex: 984X655</b>', upload_to='noticia', verbose_name='Imagem da Postagem')),
                ('data', models.DateTimeField()),
                ('descricao', ckeditor_uploader.fields.RichTextUploadingField(blank=True, verbose_name='Sua Postagem')),
                ('noticia_views', models.IntegerField(blank=True, default=0, verbose_name='Quatidade de Visualizações')),
            ],
            options={
                'verbose_name': 'UMA NOTÍCIA',
                'verbose_name_plural': 'NOTÍCIAS',
                'ordering': ['-data'],
            },
        ),
        migrations.CreateModel(
            name='Comentario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usuario', models.CharField(max_length=250, verbose_name='Usuário')),
                ('email', models.EmailField(max_length=254)),
                ('texto', models.TextField()),
                ('data_criada', models.DateTimeField(auto_now_add=True)),
                ('active', models.BooleanField(default=False)),
                ('comentario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comentarios', to='noticias.noticia')),
                ('resposta', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='respostas', to='noticias.comentario')),
            ],
            options={
                'verbose_name': 'UM COMENTÁRIO',
                'verbose_name_plural': 'COMENTÁRIO',
                'ordering': ['-data_criada'],
            },
        ),
    ]
