# Generated by Django 4.0.4 on 2023-08-13 12:11

import ckeditor_uploader.fields
import colorfield.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Filias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filial', models.CharField(max_length=300, verbose_name='Filial')),
                ('slug', models.SlugField(default=None, max_length=150, null=True, unique=True)),
                ('site', models.URLField(blank=True, help_text='se tiver site preencha so mente o link do site exe: <b>www.nomedosite.com.br</b>', null=True, verbose_name='WebSite')),
                ('logomarca', models.ImageField(help_text='Notifique-se que o tamanho da Imagem é de <b>770x770</b>', upload_to='filiais', verbose_name='Logomarca')),
                ('informativo', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='Sobre a Empresa')),
                ('endereco', models.CharField(blank=True, max_length=300, verbose_name='Endereço')),
                ('localizacao', models.CharField(blank=True, max_length=500, verbose_name='Localização do Google')),
                ('valores', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='Nossos Valores')),
                ('visao', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='nossa visão')),
                ('missao', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='nossa missão')),
                ('slide1', models.ImageField(blank=True, help_text='Notifique-se que o tamanho da Imagem é de <b>868x614</b>', null=True, upload_to='filiais/slid', verbose_name='Imagen Slide 1')),
                ('slide2', models.ImageField(blank=True, help_text='Notifique-se que o tamanho da Imagem é de <b>868x614</b>', null=True, upload_to='filiais/slid', verbose_name='Imagen Slide 2')),
                ('slide3', models.ImageField(blank=True, help_text='Notifique-se que o tamanho da Imagem é de <b>868x614</b>', null=True, upload_to='filiais/slid', verbose_name='Imagen Slide 3')),
                ('whatsapp', models.CharField(blank=True, max_length=150, verbose_name='Whatsapp')),
                ('facebook', models.URLField(blank=True, help_text='link do facebook', verbose_name='Facebook')),
                ('instagram', models.URLField(blank=True, help_text='link do instagram', verbose_name='Instagram')),
                ('youtube', models.URLField(blank=True, help_text='link do youtube', verbose_name='Youtube')),
                ('paleta_cor', colorfield.fields.ColorField(default='#1e5b9c', image_field=None, max_length=18, samples=None, verbose_name='Paleta de Cor')),
                ('filiais_views', models.IntegerField(blank=True, default=0, verbose_name='Quatidade de Visualizações')),
            ],
            options={
                'verbose_name': 'Uma Filial',
                'verbose_name_plural': 'FILIAIS',
            },
        ),
        migrations.CreateModel(
            name='Foto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen_filiais', models.ImageField(upload_to='filiais/imagens/')),
                ('data', models.DateTimeField(auto_now_add=True)),
                ('show', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='filiais.filias')),
            ],
            options={
                'ordering': ['-data'],
            },
        ),
        migrations.CreateModel(
            name='Comentario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usuario', models.CharField(max_length=250, verbose_name='Usuário')),
                ('email', models.EmailField(max_length=254)),
                ('texto', models.TextField()),
                ('data_criada', models.DateTimeField(auto_now_add=True)),
                ('active', models.BooleanField(default=False)),
                ('comentario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comentarios', to='filiais.filias')),
                ('resposta', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='respostas', to='filiais.comentario')),
            ],
            options={
                'verbose_name': 'UM COMENTÁRIO',
                'verbose_name_plural': 'COMENTÁRIO',
                'ordering': ['-data_criada'],
            },
        ),
    ]
